language: cpp
compiler: gcc
sudo: require
dist: xenial

install:
  - sudo apt-get -y install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python

script:
  - chmod +x files/etc/uci-defaults/*
  # wget -c "https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa7/openwrt-imagebuilder-sunxi-cortexa7.Linux-x86_64.tar.xz" # 45 MB
  - wget -c "https://github.com/melsem/openwrt/blob/master/openwrt-imagebuilder-sunxi-cortexa7.Linux-i686.tar.xz?raw=true" --trust-server-names
  - tar xf openwrt-imagebuilder-*.tar.xz
  - cd openwrt-imagebuilder-*/
  - |
    make image PROFILE=xunlong_orangepi-zero \
    PACKAGES="nano  uhttpd luci-mod-admin-full luci-base libiwinfo-lua luci-theme-bootstrap -dnsmasq -firewall -ip6tables -iptables -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -odhcp6c kmod-ipt-offload" \
    FILES=../files/ \
    EXTRA_IMAGE_NAME="custom"
  # luci-proto-wireguard luci-app-wireguard wireguard kmod-wireguard wireguard-tools

after_success:
  - find ./bin/targets/ -type f -exec ls -lh {} \;
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./bin/targets/*/*/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
